import { defineConfig, type OxlintConfig } from "oxlint";

const readonlyAllowances = [
  {
    from: "lib",
    name: [
      "Promise",
      "PromiseLike",
      "Request",
      "RequestInit",
      "RequestInfo",
      "Response",
      "ResponseInit",
      "Headers",
      "HeadersInit",
      "URL",
      "URLSearchParams",
      "AbortController",
      "AbortSignal",
      "Blob",
      "File",
      "FormData",
      "ReadableStream",
      "ReadableStreamDefaultReader",
      "ReadableStreamBYOBReader",
      "ReadableStreamDefaultController",
      "ReadableByteStreamController",
      "ReadableStreamBYOBRequest",
      "WritableStream",
      "WritableStreamDefaultWriter",
      "WritableStreamDefaultController",
      "TransformStream",
      "TransformStreamDefaultController",
    ],
  },
  // ES2024 (without DOM) uses Node web globals, some merged with Undici declarations.
  {
    from: "package",
    package: "node",
    name: [
      "AbortController",
      "AbortSignal",
      "Request",
      "RequestInit",
      "RequestInfo",
      "Response",
      "ResponseInit",
      "Headers",
      "HeadersInit",
      "URL",
      "URLSearchParams",
      "Blob",
      "File",
      "FormData",
      "ReadableStream",
      "ReadableStreamDefaultReader",
      "ReadableStreamBYOBReader",
      "ReadableStreamDefaultController",
      "ReadableByteStreamController",
      "ReadableStreamBYOBRequest",
      "WritableStream",
      "WritableStreamDefaultWriter",
      "WritableStreamDefaultController",
      "TransformStream",
      "TransformStreamDefaultController",
      "IncomingMessage",
      "ServerResponse",
      "TestContext",
    ],
  },
  {
    from: "package",
    package: "undici-types",
    name: [
      "Request",
      "RequestInit",
      "RequestInfo",
      "Response",
      "ResponseInit",
      "Headers",
      "HeadersInit",
      "FormData",
    ],
  },
  {
    from: "package",
    package: "@earendil-works/pi-coding-agent",
    name: ["AgentSession", "ModelRegistry"],
  },
  // The explicit lifecycle owner advances its SDK handles and queues.
  { from: "file", path: "src/servers.ts", name: "ManagedServer" },
] satisfies Extract<
  NonNullable<NonNullable<OxlintConfig["rules"]>["typescript/prefer-readonly-parameter-types"]>,
  [unknown, unknown]
>[1]["allow"];

const readonlyParameters = {
  checkParameterProperties: true,
  ignoreInferredTypes: true,
  treatMethodsAsReadonly: false,
  allow: readonlyAllowances,
};

export default defineConfig({
  plugins: ["eslint", "typescript", "unicorn", "oxc", "import", "promise", "node", "vitest"],
  categories: {
    correctness: "error",
    suspicious: "error",
    perf: "error",
    pedantic: "off",
    style: "off",
    restriction: "off",
    nursery: "off",
  },
  options: {
    typeAware: true,
    typeCheck: true,
    denyWarnings: true,
    reportUnusedDisableDirectives: "error",
    respectEslintDisableDirectives: false,
  },
  rules: {
    "typescript/no-explicit-any": ["error", { fixToUnknown: false, ignoreRestArgs: false }],
    "typescript/no-non-null-assertion": "error",
    "typescript/no-unsafe-type-assertion": "error",
    "typescript/no-unnecessary-type-assertion": ["error", { checkLiteralConstAssertions: true }],
    "typescript/consistent-type-assertions": [
      "error",
      {
        assertionStyle: "as",
        objectLiteralTypeAssertions: "never",
        arrayLiteralTypeAssertions: "never",
      },
    ],
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-wrapper-object-types": "error",
    "typescript/no-invalid-void-type": [
      "error",
      { allowAsThisParameter: true, allowInGenericTypeArguments: true },
    ],
    "typescript/no-unnecessary-type-parameters": "error",
    "typescript/no-deprecated": "error",
    "typescript/unbound-method": "error",
    "typescript/no-misused-spread": "error",
    "typescript/no-for-in-array": "error",
    "typescript/require-array-sort-compare": "error",
    "typescript/ban-ts-comment": [
      "error",
      {
        "ts-check": false,
        "ts-expect-error": true,
        "ts-ignore": true,
        "ts-nocheck": true,
      },
    ],
    "typescript/strict-boolean-expressions": [
      "error",
      {
        allowAny: false,
        allowNullableBoolean: false,
        allowNullableEnum: false,
        allowNullableNumber: false,
        allowNullableObject: true,
        allowNullableString: false,
        allowNumber: false,
        allowString: false,
      },
    ],
    "typescript/no-unnecessary-condition": [
      "error",
      { checkTypePredicates: true, allowConstantLoopConditions: "only-allowed-literals" },
    ],
    "typescript/switch-exhaustiveness-check": [
      "error",
      { considerDefaultExhaustiveForUnions: false },
    ],
    eqeqeq: ["error", "always"],
    "no-implicit-coercion": "error",
    "typescript/restrict-plus-operands": [
      "error",
      {
        allowAny: false,
        allowBoolean: false,
        allowNullish: false,
        allowNumberAndString: false,
        allowRegExp: false,
        skipCompoundAssignments: false,
      },
    ],
    "typescript/restrict-template-expressions": [
      "error",
      {
        allowAny: false,
        allowArray: false,
        allowBoolean: true,
        allowNever: false,
        allowNullish: false,
        allowNumber: true,
        allowRegExp: false,
      },
    ],
    "typescript/no-base-to-string": ["error", { checkUnknown: true }],
    "typescript/no-floating-promises": [
      "error",
      {
        checkThenables: true,
        ignoreIIFE: false,
        ignoreVoid: false,
        allowForKnownSafeCalls: [],
        allowForKnownSafePromises: [],
      },
    ],
    "typescript/no-misused-promises": "error",
    "typescript/await-thenable": "error",
    "typescript/return-await": ["error", "error-handling-correctness-only"],
    "typescript/strict-void-return": ["error", { allowReturnAny: false }],
    "typescript/no-confusing-void-expression": [
      "error",
      {
        ignoreArrowShorthand: true,
        ignoreVoidOperator: false,
        ignoreVoidReturningFunctions: false,
      },
    ],
    "typescript/no-meaningless-void-operator": "error",
    "promise/always-return": ["error", { ignoreLastCallback: true, ignoreAssignmentVariable: [] }],
    "promise/catch-or-return": "error",
    "no-await-in-loop": "error",
    "typescript/only-throw-error": [
      "error",
      {
        allowThrowingAny: false,
        allowThrowingUnknown: false,
        allowRethrowing: true,
      },
    ],
    "typescript/use-unknown-in-catch-callback-variable": "error",
    "typescript/prefer-promise-reject-errors": [
      "error",
      {
        allowEmptyReject: false,
        allowThrowingAny: false,
        allowThrowingUnknown: false,
      },
    ],
    "no-useless-catch": "error",
    "no-param-reassign": ["error", { props: true }],
    "typescript/prefer-readonly": "error",
    "typescript/prefer-readonly-parameter-types": ["error", readonlyParameters],
    "typescript/explicit-module-boundary-types": "error",
    "typescript/method-signature-style": ["error", "property"],
    "typescript/consistent-type-imports": [
      "error",
      { prefer: "type-imports", fixStyle: "inline-type-imports", disallowTypeAnnotations: true },
    ],
    "typescript/consistent-type-exports": "error",
    "typescript/no-import-type-side-effects": "error",
    "import/no-cycle": [
      "error",
      { ignoreTypes: false, ignoreExternal: false, allowUnsafeDynamicCyclicDependency: false },
    ],
    "import/no-self-import": "error",
    "import/no-duplicates": ["error", { preferInline: true }],
    "import/no-mutable-exports": "error",
    complexity: ["error", { max: 10, variant: "modified" }],
    "max-depth": ["error", { max: 3 }],
    "max-params": ["error", { max: 4 }],
    "max-statements": ["error", { max: 40 }],
    "max-lines-per-function": [
      "error",
      { max: 80, skipBlankLines: true, skipComments: true, IIFEs: true },
    ],
    "max-lines": ["error", { max: 500, skipBlankLines: true, skipComments: true }],
    curly: ["error", "all"],
    "no-var": "error",
    "prefer-const": "error",
    "no-nested-ternary": "error",
    "no-return-assign": ["error", "always"],
    "no-sequences": "error",
    "no-multi-assign": "error",
    "no-else-return": "error",
    "no-eval": "error",
    "no-implied-eval": "error",
    "no-new-func": "error",
    "no-with": "error",
    "no-debugger": "error",
    "no-control-regex": "error",
    "no-empty": ["error", { allowEmptyCatch: false }],
    "no-empty-function": "error",
    "unicorn/no-useless-undefined": "error",
    "unicorn/no-abusive-eslint-disable": "error",
    "require-await": "off",
    "typescript/require-await": "off",
    "typescript/consistent-return": "off",
    "no-underscore-dangle": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/no-array-reverse": "off",
    // ponytail: Oxlint 1.87 does not recognize node:test or Node assertions; these guard Vitest forms only. Requalify when native support lands.
    "vitest/expect-expect": [
      "error",
      {
        assertFunctionNames: [
          "expect",
          "expectTypeOf",
          "assert",
          "assert.*",
          "assertType",
          "verifySearch",
          "verifyPrivateOutput",
          "verifyVisionConfiguration",
          "verifyReload",
        ],
        additionalTestBlockFunctions: ["t.test"],
      },
    ],
    "vitest/no-conditional-expect": "error",
  },
  overrides: [
    {
      files: [
        "**/*.test.{js,jsx,ts,tsx,mjs,cjs,mts,cts}",
        "**/*.spec.{js,jsx,ts,tsx,mjs,cjs,mts,cts}",
        "**/__tests__/**/*.{js,jsx,ts,tsx,mjs,cjs,mts,cts}",
        "**/*.test-d.ts",
        "scripts/smoke.mjs",
        "test/fixtures/vision-offline.mjs",
        "test/quality-fixtures.mjs",
      ],
      rules: {
        "typescript/no-unnecessary-condition": [
          "error",
          { checkTypePredicates: false, allowConstantLoopConditions: "only-allowed-literals" },
        ],
        complexity: ["error", { max: 15, variant: "modified" }],
        "max-depth": ["error", { max: 4 }],
        "max-params": ["error", { max: 6 }],
        "max-statements": "off",
        "max-lines-per-function": "off",
        "max-lines": "off",
      },
    },
    {
      files: ["scripts/smoke.mjs", "test/native-runtime.test.mjs"],
      rules: {
        // Native execute has optional positional arguments; negative inputs test absence explicitly.
        "unicorn/no-useless-undefined": ["error", { checkArguments: false }],
      },
    },
    {
      files: ["**/*.d.{ts,mts,cts}"],
      rules: {
        complexity: "off",
        "max-depth": "off",
        "max-params": "off",
        "max-statements": "off",
        "max-lines-per-function": "off",
        "max-lines": "off",
      },
    },
    {
      files: ["**/*.test-d.ts"],
      rules: {
        "typescript/ban-ts-comment": [
          "error",
          {
            "ts-check": false,
            "ts-expect-error": "allow-with-description",
            "ts-ignore": true,
            "ts-nocheck": true,
            minimumDescriptionLength: 10,
          },
        ],
        "typescript/no-unnecessary-condition": [
          "error",
          { checkTypePredicates: false, allowConstantLoopConditions: "only-allowed-literals" },
        ],
      },
    },
    {
      files: ["src/auth.ts"],
      rules: {
        // Native auth may execute commands or refresh; stop at the first key, never run later providers concurrently.
        "no-await-in-loop": "off",
      },
    },
    {
      files: ["src/index.ts"],
      rules: {
        // Only the explicit ManagedServer owner parameter advances lifecycle state.
        "no-param-reassign": ["error", { props: true, ignorePropertyModificationsFor: ["owner"] }],
      },
    },
    {
      files: ["scripts/smoke.mjs"],
      rules: {
        // The smoke temporarily owns stdout/stderr.write and restores it in finally.
        "no-param-reassign": ["error", { props: true, ignorePropertyModificationsFor: ["stream"] }],
        "typescript/prefer-readonly-parameter-types": [
          "error",
          {
            ...readonlyParameters,
            allow: [
              ...readonlyAllowances,
              { from: "package", package: "node", name: "WriteStream" },
            ],
          },
        ],
      },
    },
    {
      files: ["test/native-runtime.test.mjs"],
      rules: {
        // Cases share process.env and session reload/child disposal; parallel calls would test the wrong configuration.
        "no-await-in-loop": "off",
      },
    },
    {
      files: ["src/register-tool.ts"],
      rules: {
        // The native Pi execute boundary requires five SDK-owned parameters.
        "max-params": ["error", { max: 5 }],
      },
    },
  ],
});
